import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Activity, ArrowDownToLine, Check, ChevronRight, CircleHelp, FileCheck2, Gauge, Layers3, Link2, Radio, ScanLine, Wifi, WifiOff } from 'lucide-react';
import { DEFAULT_TELEMETRY_URL, EchoMazeSocket, type SocketStatus, type TelemetryMessage } from '@/lib/echo-maze-socket';
import { baselineGrid, currentGrid, diffGrid, diffZones, makePointCloud, pose, runMetadata, scores, telemetry, type RunState } from '@/lib/demo-model';
import { DashboardPanel, PanelBody } from './DashboardPanel';
import { ControlPanel } from './ControlPanel';
import { DiffHeatmap } from './DiffHeatmap';
import { FinalReport } from './FinalReport';
import { GhostMapOverlay } from './GhostMapOverlay';
import { OccupancyGridView } from './OccupancyGridView';
import { PointCloudView } from './PointCloudView';
import { ScorePanel } from './ScorePanel';
import { TelemetryPanel } from './TelemetryPanel';
import { TimeMachineSlider } from './TimeMachineSlider';

type View = 'overview' | 'telemetry' | 'analysis' | 'report';
const socket = new EchoMazeSocket();

function Panel({ title, code, children, className = '' }: { title: string; code?: string; children: ReactNode; className?: string }) {
  return <DashboardPanel title={title} code={code} className={className}>{children}</DashboardPanel>;
}

function NavButton({ view, active, icon: Icon, label, onClick }: { view: View; active: boolean; icon: typeof Activity; label: string; onClick: (view: View) => void }) {
  return <button className={`nav-button ${active ? 'active' : ''}`} onClick={() => onClick(view)} aria-current={active ? 'page' : undefined}><Icon /><span>{label}</span>{active && <ChevronRight size={12} className="nav-chevron" />}</button>;
}

function parseLiveTelemetry(message: TelemetryMessage) {
  const motor = (message.motor ?? {}) as Record<string, unknown>;
  const scan = (message.scan ?? {}) as Record<string, unknown>;
  const imu = (message.imu ?? {}) as Record<string, unknown>;
  const number = (value: unknown, fallback: number) => typeof value === 'number' && Number.isFinite(value) ? value : fallback;
  const vector = (value: unknown, fallback: string) => Array.isArray(value) && value.length === 3 ? value.map((part) => number(part, 0).toFixed(2)).join(' / ') : fallback;
  return {
    motorState: String(message.mode ?? 'LIVE TELEMETRY').toUpperCase(),
    leftMotor: number(motor.left_speed, telemetry.leftMotor), rightMotor: number(motor.right_speed, telemetry.rightMotor),
    accel: vector(imu.accel, telemetry.accel), gyro: vector(imu.gyro, telemetry.gyro),
    ultrasonic: number(scan.distance_cm, telemetry.ultrasonic), ir: number(message.ir, telemetry.ir), temperature: number(message.temp_c, telemetry.temperature),
  };
}

function Header({ connection, onLink, onReport }: { connection: SocketStatus; onLink: () => void; onReport: () => void }) {
  const live = connection === 'connected';
  const connecting = connection === 'connecting';
  return <header className="topbar"><div className="brand"><div className="brand-mark"><span /></div><div><div className="brand-wordmark">ECHO MAZE</div><div className="brand-sub">STRUCTURAL RECONNAISSANCE / 01</div></div></div><div className="top-meta"><button className={`connection connection-button ${live ? 'is-live' : connecting ? 'is-connecting' : ''}`} onClick={onLink} title={live ? 'Disconnect from telemetry receiver' : `Connect to ${DEFAULT_TELEMETRY_URL}`}>{live ? <Wifi size={13} /> : connecting ? <Radio size={13} /> : <WifiOff size={13} />}<i className="live-dot" />{live ? 'LIVE LINK' : connecting ? 'CONNECTING' : 'LOCAL REPLAY'}</button><span className="top-timestamp">14:32:08 UTC · PACKET 1,842</span><button className="top-action report-top-action" onClick={onReport}><ArrowDownToLine size={11} /> REPORT</button></div></header>;
}

function RunFacts() {
  return <Panel title="Run ledger" code="CHAIN OF CUSTODY"><PanelBody className="run-ledger"><div><span>ACTIVE CASE</span><strong>{runMetadata.id}</strong></div><div><span>BASELINE</span><strong>MAZE-ALPHA / v.01</strong></div><div><span>ROUTE</span><strong>{runMetadata.route}</strong></div><div><span>CAPTURE WINDOW</span><strong>00:02:14</strong></div><div><span>MODEL</span><strong>ISOLATION FOREST · v1</strong></div><div className="ledger-seal"><Check size={13} /> RAW PACKETS IMMUTABLE</div></PanelBody></Panel>;
}

function Overview({ state, progress, connected, liveTelemetry, packetCount, onCommand, onView, ghostOn, onToggleGhost, frame }: { state: RunState; progress: number; connected: boolean; liveTelemetry: ReturnType<typeof parseLiveTelemetry> | null; packetCount: number; onCommand: (command: 'learn' | 'verify' | 'stop' | 'reset') => void; onView: (view: View) => void; ghostOn: boolean; onToggleGhost: () => void; frame: number }) {
  const visibleTelemetry = liveTelemetry ?? telemetry;
  const points = useMemo(() => makePointCloud(frame / 9), [frame]);
  return <div className="view-stack"><div className="overview-grid"><Panel title="Live occupancy / ghost map" code="REGISTERED SPACE" className="map-panel"><PanelBody className="map-panel-body"><div className="map-toolbar"><span><span className="status-chip"><i /> {state === 'LEARNING' || state === 'VERIFYING' ? 'ACQUIRING' : 'MAP LOCKED'}</span><span className="toolbar-muted">16 × 10 CELLS · 1 m GRID</span></span><button className="ghost-button" onClick={onToggleGhost}>{ghostOn ? 'GHOST ON' : 'GHOST OFF'}</button></div><GhostMapOverlay baseline={baselineGrid} current={currentGrid} pose={pose} enabled={ghostOn} onToggle={onToggleGhost} interpolation={state === 'LEARNING' ? Math.max(.1, progress / 100) : state === 'VERIFYING' ? 1 : .72} /><div className="map-footer"><span>POSE {pose.x.toFixed(2)}m / {pose.y.toFixed(2)}m · HDG {pose.heading}°</span><strong>{pose.confidence.toFixed(1)}% POSE CONFIDENCE</strong></div></PanelBody></Panel><div className="overview-rail"><ControlPanel state={state} progress={progress} connected={connected} onCommand={onCommand} /><ScorePanel scores={scores} /></div></div><div className="overview-lower"><PointCloudView points={points} pose={pose} scanning={state === 'LEARNING' || state === 'VERIFYING'} /><TelemetryPanel telemetry={visibleTelemetry} connected={connected} packetCount={packetCount} source={liveTelemetry ? 'ESP32 / LIVE' : 'DEMO FIXTURE'} /></div><div className="overview-facts"><RunFacts /><Panel title="Evidence pulse" code="LAST 60 SEC"><PanelBody className="evidence-pulse"><div className="pulse-chart" aria-label="Recent anomaly score trend">{Array.from({ length: 42 }, (_, index) => <i key={index} style={{ height: `${18 + ((index * 17 + frame) % 64)}%`, opacity: .35 + (index % 5) / 10 }} />)}</div><div className="pulse-footer"><span><Activity size={13} /> STREAM HEALTH <b>99.8%</b></span><span>WINDOW SCORE <b>{scores.total}/100</b></span></div></PanelBody></Panel></div><div className="footer-strip"><span><Check size={11} /> LOCAL MODEL READY</span><span>WS BOUNDARY · {connected ? 'RECEIVING LIVE FRAMES' : 'AWAITING HARDWARE LINK'}</span><button onClick={() => onView('analysis')}>OPEN ANALYSIS <ChevronRight size={11} /></button></div></div>;
}

function TelemetryWorkspace({ connected, liveTelemetry, packetCount, frame }: { connected: boolean; liveTelemetry: ReturnType<typeof parseLiveTelemetry> | null; packetCount: number; frame: number }) {
  return <div className="view-stack"><div className="workspace-heading"><div><div className="eyebrow">SIGNAL INSPECTOR</div><h1 className="page-title">RAW TELEMETRY</h1><p className="page-subtitle">Inspect the sensor stream before it becomes map geometry or model evidence.</p></div><div className="workspace-stamp"><Radio size={14} /><span>{connected ? 'WEBSOCKET FRAME STREAM' : 'DETERMINISTIC LOCAL REPLAY'}</span><strong>{packetCount.toLocaleString()} frames</strong></div></div><div className="telemetry-workspace-grid"><TelemetryPanel telemetry={liveTelemetry ?? telemetry} connected={connected} packetCount={packetCount} source={liveTelemetry ? 'ESP32 / LIVE' : 'DEMO FIXTURE'} /><PointCloudView points={makePointCloud(frame / 9)} pose={pose} scanning={connected} /><Panel title="Packet anatomy" code="CONTRACT V1"><PanelBody className="packet-anatomy"><div className="packet-row"><span>RUN ID</span><strong>{runMetadata.id}</strong><em>STRING</em></div><div className="packet-row"><span>TIMESTAMP</span><strong>{(Date.now() % 100000).toLocaleString()} ms</strong><em>MONOTONIC</em></div><div className="packet-row"><span>MODE</span><strong>{liveTelemetry?.motorState ?? 'TEST / FIXTURE'}</strong><em>LEARN · VERIFY</em></div><div className="packet-row"><span>IMU</span><strong>{liveTelemetry ? '3-AXIS / VALID' : 'CANONICAL SAMPLE'}</strong><em>ACCEL + GYRO</em></div><div className="packet-row"><span>OPTIONAL</span><strong>SCAN · IR · TEMP</strong><em>NULL SAFE</em></div><div className="packet-note"><CircleHelp size={14} /><span>Fixture packets validate connectivity only. Real learn/verify packets must carry live IMU readings.</span></div></PanelBody></Panel></div></div>;
}

function Analysis({ state, ghostOn, onToggleGhost }: { state: RunState; ghostOn: boolean; onToggleGhost: () => void }) {
  const [time, setTime] = useState(72);
  const blended = currentGrid.map((value, index) => baselineGrid[index] * (1 - time / 100) + value * (time / 100));
  return <div className="view-stack"><div className="workspace-heading"><div><div className="eyebrow">SPATIAL FORENSICS</div><h1 className="page-title">MAP / ANALYSIS</h1><p className="page-subtitle">Compare the baseline fingerprint with the verification run, cell by cell.</p></div><div className="analysis-tags"><span>BASELINE LOCKED</span><span className="tag-alert">2 REVIEW ZONES</span></div></div><div className="analysis-grid"><Panel title="Time-machine occupancy" code="INTERPOLATED GRID" className="analysis-map-panel"><PanelBody className="analysis-map-body"><div className="map-toolbar"><span><Layers3 size={13} /> MAP MORPH / {time}% CURRENT</span><button className="ghost-button" onClick={onToggleGhost}>{ghostOn ? 'GHOST ON' : 'GHOST OFF'}</button></div><div className="analysis-grid-canvas"><OccupancyGridView values={blended} pose={pose} ghostValues={ghostOn ? baselineGrid : undefined} /></div><TimeMachineSlider value={time} onChange={setTime} /></PanelBody></Panel><DiffHeatmap values={diffGrid} zones={diffZones} /></div><div className="analysis-bottom"><Panel title="Baseline / current comparison" code="RUN PAIR"><PanelBody className="side-by-side"><div><span>BASELINE</span><strong>MAZE-ALPHA</strong><small>healthy reference · 1,901 pts</small><OccupancyGridView values={baselineGrid} mode="baseline" compact /></div><div><span>CURRENT</span><strong>EM-0427-VR</strong><small>verification capture · 1,842 pts</small><OccupancyGridView values={currentGrid} mode="current" compact /></div></PanelBody></Panel><Panel title="Change interpretation" code="MODEL NOTES"><PanelBody className="interpretation"><div><i className="interpretation-icon cyan">01</i><p><strong>Geometry leads.</strong> East wall displacement is the strongest evidence signal.</p></div><div><i className="interpretation-icon violet">02</i><p><strong>Vibration corroborates.</strong> A high-energy window supports the spatial change.</p></div><div><i className="interpretation-icon amber">03</i><p><strong>Human review remains final.</strong> Anomaly detection is an early-warning aid.</p></div></PanelBody></Panel></div><div className="footer-strip"><span><Check size={11} /> FUSION READY</span><span>DIFF THRESHOLD · 0.35</span><span>FFT WINDOW · 2.0 SEC</span></div></div>;
}

export function EchoMazeDashboard() {
  const [view, setView] = useState<View>('overview');
  const [state, setState] = useState<RunState>('IDLE');
  const [progress, setProgress] = useState(72);
  const [commandNote, setCommandNote] = useState('Awaiting command');
  const [connection, setConnection] = useState<SocketStatus>('disconnected');
  const [liveTelemetry, setLiveTelemetry] = useState<ReturnType<typeof parseLiveTelemetry> | null>(null);
  const [packetCount, setPacketCount] = useState(1842);
  const [ghostOn, setGhostOn] = useState(true);
  const [frame, setFrame] = useState(0);
  const [noticeOpen, setNoticeOpen] = useState(false);
  useEffect(() => { const unsubscribeStatus = socket.onStatus(setConnection); const unsubscribeTelemetry = socket.onTelemetry((message) => { setLiveTelemetry(parseLiveTelemetry(message)); setPacketCount((count) => count + 1); }); return () => { unsubscribeStatus(); unsubscribeTelemetry(); }; }, []);
  useEffect(() => { const timer = window.setInterval(() => setFrame((value) => value + 1), 1200); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (state !== 'LEARNING' && state !== 'VERIFYING') return; const timer = window.setInterval(() => setProgress((value) => { if (value >= 100) { setState('COMPLETE'); setCommandNote('Route complete · evidence ready'); return 100; } return Math.min(100, value + 2); }), 750); return () => window.clearInterval(timer); }, [state]);
  const command = (next: 'learn' | 'verify' | 'stop' | 'reset') => { const delivered = socket.send(next); if (next === 'learn') { setState('LEARNING'); setProgress(14); setCommandNote(delivered ? 'Baseline command sent to rover' : 'Baseline capture staged in local replay'); } if (next === 'verify') { setState('VERIFYING'); setProgress(58); setCommandNote(delivered ? 'Verification command sent to rover' : 'Verification staged in local replay'); } if (next === 'stop') { setState('STOPPED'); setCommandNote('Run halted by operator'); } if (next === 'reset') { setState('IDLE'); setProgress(72); setCommandNote('Awaiting command'); } };
  const link = () => { if (connection === 'connected' || connection === 'connecting') socket.disconnect(); else socket.connect(); };
  const nav = [{ view: 'overview' as View, icon: Gauge, label: 'Live cockpit' }, { view: 'telemetry' as View, icon: Radio, label: 'Signal inspector' }, { view: 'analysis' as View, icon: Layers3, label: 'Map / analysis' }, { view: 'report' as View, icon: FileCheck2, label: 'Final report' }];
  const titles: Record<View, [string, string]> = { overview: ['LIVE INSPECTION', 'Structural verification cockpit'], telemetry: ['RAW TELEMETRY', 'Sensor stream and point registration'], analysis: ['MAP / ANALYSIS', 'Baseline comparison and anomaly evidence'], report: ['FINAL REPORT', 'Judge-ready structural verification summary'] };
  return <div className="app-shell"><Header connection={connection} onLink={link} onReport={() => setView('report')} /><div className="mobile-nav">{nav.map((item) => <NavButton key={item.view} {...item} active={view === item.view} onClick={setView} />)}</div><div className="body-layout"><aside className="sidebar"><div className="nav-kicker">INSPECTION CONSOLE <span>v0.1</span></div><nav className="nav-list">{nav.map((item) => <NavButton key={item.view} {...item} active={view === item.view} onClick={setView} />)}</nav><div className="sidebar-status"><div className="status-orbit"><span /><span /><span /></div><div><strong>EM-RVR-01</strong><small>{connection === 'connected' ? 'LINKED / RECEIVING' : 'LOCAL / STANDBY'}</small></div></div><div className="sidebar-footer"><div className="side-unit">ENVIRONMENT<br /><strong>MAZE-ALPHA</strong></div><div className="side-unit" style={{ marginTop: 12 }}>RUN MODE<br /><strong>{state}</strong></div><button className="notice-link" onClick={() => setNoticeOpen(true)}><Link2 size={11} /> CONNECTION NOTICE</button></div></aside><main className="main"><div className="view-heading"><div><div className="eyebrow">ECHO MAZE / {connection === 'connected' ? 'LIVE BUS' : 'LOCAL BUS'}</div><h1 className="page-title">{titles[view][0]}</h1><p className="page-subtitle">{titles[view][1]} · {commandNote}.</p></div><div className={`run-chip ${state === 'VERIFYING' || state === 'STOPPED' ? 'review' : ''}`}><span className="live-dot" />{state === 'IDLE' ? 'READY FOR COMMAND' : state === 'STOPPED' ? 'RUN HALTED' : `${state} · ${runMetadata.id}`}</div></div>{view === 'overview' && <Overview state={state} progress={progress} connected={connection === 'connected'} liveTelemetry={liveTelemetry} packetCount={packetCount} onCommand={command} onView={setView} ghostOn={ghostOn} onToggleGhost={() => setGhostOn((value) => !value)} frame={frame} />}{view === 'telemetry' && <TelemetryWorkspace connected={connection === 'connected'} liveTelemetry={liveTelemetry} packetCount={packetCount} frame={frame} />}{view === 'analysis' && <Analysis state={state} ghostOn={ghostOn} onToggleGhost={() => setGhostOn((value) => !value)} />}{view === 'report' && <FinalReport metadata={runMetadata} scores={scores} onExport={() => setCommandNote('Report staged for export')} />}<div className="floating-status"><Activity size={12} /> {connection === 'connected' ? 'RECEIVING' : 'REPLAYING'} · {packetCount.toLocaleString()} FRAMES</div></main></div>{noticeOpen && <div className="modal-shade"><div className="privacy-modal" role="dialog" aria-labelledby="privacy-title"><h2 id="privacy-title">Connection boundary</h2><p>The console can run locally with deterministic replay data, or connect to the laptop receiver at <code>{DEFAULT_TELEMETRY_URL}</code>. Raw telemetry stays in the Echo-Maze workspace.</p><button onClick={() => setNoticeOpen(false)}><Check size={12} /> CLOSE NOTICE</button></div></div>}</div>;
}
