import { AlertTriangle, Download, FileCheck2, ShieldCheck } from 'lucide-react';
import { DashboardPanel, PanelBody } from './DashboardPanel';
import type { RunMetadata, ScoreSet } from '@/lib/demo-model';

export function FinalReport({ metadata, scores, onExport }: { metadata: RunMetadata; scores: ScoreSet; onExport: () => void }) {
  const similarity = 100 - scores.total * 0.245;
  const severity = scores.total >= 65 ? 'HIGH' : scores.total >= 35 ? 'MODERATE' : 'LOW';
  const geometryAgreement = Math.max(0, 100 - scores.geometry);
  const routeCoverage = scores.source === 'live-evidence' ? Math.max(0, 100 - scores.geometry * 0.35) : 96.2;
  const criticalZones = scores.total >= 65 ? '3 / 3' : scores.total >= 35 ? '2 / 3' : '0 / 3';
  const pointsCompared = scores.source === 'live-evidence' ? 'Live telemetry' : '1,842 / 1,901';
  const bannerTitle = severity === 'LOW' ? 'NO CRITICAL CHANGE FLAG' : 'INSPECTION REQUIRED';
  return <div className="report-content"><div className="report-banner"><AlertTriangle size={24} /><div><strong>{bannerTitle}</strong><p>{scores.note ?? 'Evidence is ready for a human inspection decision.'}</p></div><span>CASE {metadata.id}</span></div><div className="report-grid"><DashboardPanel title="Verification result" code="SIGNED EVIDENCE"><PanelBody><div className="report-result"><div className="similarity-ring" style={{ background: `conic-gradient(var(--signal) 0 ${similarity}%, var(--line) ${similarity}% 100%)` }}><div className="similarity-number">{similarity.toFixed(1)}<small>MAP SIMILARITY</small></div></div><div className="report-stats"><div><span>GEOMETRY AGREEMENT</span><strong>{geometryAgreement.toFixed(1)}%</strong></div><div><span>ROUTE COVERAGE</span><strong>{routeCoverage.toFixed(1)}%</strong></div><div><span>POINTS COMPARED</span><strong>{pointsCompared}</strong></div><div><span>CRITICAL ZONES</span><strong className="critical">{criticalZones}</strong></div></div></div><button className="export-button" onClick={onExport}><Download size={14} /> EXPORT INSPECTION REPORT</button></PanelBody></DashboardPanel><DashboardPanel title="Evidence record" code="RUN METADATA"><PanelBody className="evidence-record"><div><span>RUN IDENTIFIER</span><strong>{metadata.id}</strong></div><div><span>VERIFICATION MODE</span><strong>{metadata.mode}</strong></div><div><span>ROUTE DEFINITION</span><strong>{metadata.route}</strong></div><div><span>CAPTURED</span><strong>{metadata.startedAt}</strong></div><div><span>BASELINE FINGERPRINT</span><strong>{scores.source === 'live-evidence' ? 'Learn stream / live' : 'ALPHA-7F2C'}</strong></div><div><span>MODEL DECISION</span><strong className="critical">{scores.total} / {severity}</strong></div><div className="evidence-seal"><ShieldCheck size={17} /><span>RAW TELEMETRY IMMUTABLE<br /><b>CHAIN OF CUSTODY READY</b></span></div></PanelBody></DashboardPanel></div><div className="report-footnote"><FileCheck2 size={13} /> Echo-Maze is an early-warning inspection aid, not a structural-engineering certification.</div></div>;
}
